name: AVR make
description: Build avr based project with avr toolchain
author: Denis Bazhenov <dotsid@gmail.com>
branding:
  icon: terminal
  color: black
inputs:
  dir:
    description: directory in which to run make
    default: '.'
    required: false
    type: string
  extra_cflags:
    description: to be appended to CFLAGS in the makefile
    required: false
    type: string
  target:
    description: target to make
    required: true
    type: string
runs:
  using: docker
  image: docker://lpodkalicki/avr-toolchain
  entrypoint: make 
  args: ['--directory=${{inputs.dir}}', 'echo "CFLAGS+=${{inputs.extra_cflags}}"', '${{inputs.target}}']
